Add gres option in SBATCH specs to run jupyternotebooks on gpus
kaspermunch/slurm-jupyter pull request #4
Opened 2022-08-05 08:52 UTC by MoiColl

I added the spec `gres` in the SBATCH specs such that jupyternotebooks can be run on GPUs, as described in #2. This only happens when the user sets the option `queue` to gpu. 

Potentially, `gres` can be set up to the number of GPU nodes the cluster has (4 in the case of GenomeDK). For example, for 2 gpu nodes the SBATCH spec should be defined as `'#SBATCH --gres=gpu:2'`. This could be another user-defined option, but I don't think anyone wants to run jupiternotebooks on 4 GPUs... So, I don't think this needs to be done unless someone requests it. 

Additionally, I modified the variable `url` to `spec['url']` in the function `open_browser()` since it was creating a bug when I run the script on my local computer: the function was trying to open the URL `url` on Chrome, but such variable didn't exist since it is actually `spec['url']`.

2022-08-08 11:39 UTC, kaspermunch requested changes
Can you take out the url changes you did? I fixed that myself in a different way.

2022-08-09 09:06 UTC, MoiColl commented
Hi Kasper, 

I've reverted back those changes involving url variable. However, when I run with the previous configuration, this is the error message I get:

`$ slurm-jupyter -e sNNt_au -A GenerationInterval -u moicoll -C -t 08:00:00 -m 8g`

![image](https://user-images.githubusercontent.com/18718522/183609312-53711afa-903c-42db-864b-20117c620c7c.png)
 
When you say that you fixed this issue in a different way, is it because you have another version of the code uploaded in the repository that conda downloads from?

2022-08-10 10:34 UTC, kaspermunch commented
Try to install version 2.3.1 and see if you get the same error

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 9 Aug 2022, 11.06 +0200, Moisès Coll Macià ***@***.***>, wrote:

Hi Kasper,

I've reverted back those changes involving url variable. However, when I run with the previous configuration, this is the error message I get:

$ slurm-jupyter -e sNNt_au -A GenerationInterval -u moicoll -C -t 08:00:00 -m 8g

[image]<https://user-images.githubusercontent.com/18718522/183609312-53711afa-903c-42db-864b-20117c620c7c.png>

When you say that you fixed this issue in a different way, is it because you have another version of the code uploaded in the repository that conda downloads from?

—
Reply to this email directly, view it on GitHub<https://github.com/kaspermunch/slurm-jupyter/pull/4#issuecomment-1209115635>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAI46BF7YHCYGCURC43USZLVYINQXANCNFSM55VKJ3HA>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-08-10 10:35 UTC, kaspermunch commented
conda install -c kaspermunch -c conda-forge slurm-jupyter=2.3.1

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 10 Aug 2022, 12.34 +0200, Kasper Munch Terkelsen ***@***.***>, wrote:
Try to install version 2.3.1 and see if you get the same error

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 9 Aug 2022, 11.06 +0200, Moisès Coll Macià ***@***.***>, wrote:

Hi Kasper,

I've reverted back those changes involving url variable. However, when I run with the previous configuration, this is the error message I get:

$ slurm-jupyter -e sNNt_au -A GenerationInterval -u moicoll -C -t 08:00:00 -m 8g

[image]<https://user-images.githubusercontent.com/18718522/183609312-53711afa-903c-42db-864b-20117c620c7c.png>

When you say that you fixed this issue in a different way, is it because you have another version of the code uploaded in the repository that conda downloads from?

—
Reply to this email directly, view it on GitHub<https://github.com/kaspermunch/slurm-jupyter/pull/4#issuecomment-1209115635>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAI46BF7YHCYGCURC43USZLVYINQXANCNFSM55VKJ3HA>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-08-10 11:08 UTC, MoiColl commented
Works perfectly fine! 

What I meant is that I run into this issue only if I use the github version instead of the conda installed version.

2022-08-10 11:18 UTC, kaspermunch commented
Ok. I must have updated the git version since you cloned it then. The new version lets you run multiple instances of slurm-jupyter in different condo environments. It checks if ports are busy and finds a port that is available. It is a new feature so if there are any problems let me know. For now it only works on Mac.

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 10 Aug 2022, 13.09 +0200, Moisès Coll Macià ***@***.***>, wrote:

Works perfectly fine!

What I meant is that I run into this issue only if I use the github version instead of the conda installed version.

—
Reply to this email directly, view it on GitHub<https://github.com/kaspermunch/slurm-jupyter/pull/4#issuecomment-1210522781>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAI46BHKCXMV2DRCYH6OCCDVYOEVBANCNFSM55VKJ3HA>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-08-10 11:37 UTC, MoiColl commented
That is right. I can see that you committed changes (6th, 7th and 8th of August) after I forked your repo (5th of August). Do you want me to fork the repo, commit the changes and pull request again?

2022-08-10 12:01 UTC, merged

2022-08-10 12:01 UTC, kaspermunch commented
No I don’t think so. I’ll merge it. Thanks.

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 10 Aug 2022, 13.37 +0200, Moisès Coll Macià ***@***.***>, wrote:

That is right. I can see that you committed changes (6th, 7th and 8th of August) after I forked your repo (5th of August). Do you want me to fork the repo, commit the changes and pull request again?

—
Reply to this email directly, view it on GitHub<https://github.com/kaspermunch/slurm-jupyter/pull/4#issuecomment-1210552754>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAI46BBVZSHIUYWHBYDZRCDVYOH75ANCNFSM55VKJ3HA>.
You are receiving this because you commented.Message ID: ***@***.***>

2022-08-10 12:05 UTC, kaspermunch commented
I will build a new condo package. It will be version 2.4.0

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 10 Aug 2022, 14.01 +0200, Kasper Munch Terkelsen ***@***.***>, wrote:
No I don’t think so. I’ll merge it. Thanks.

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 10 Aug 2022, 13.37 +0200, Moisès Coll Macià ***@***.***>, wrote:

That is right. I can see that you committed changes (6th, 7th and 8th of August) after I forked your repo (5th of August). Do you want me to fork the repo, commit the changes and pull request again?

—
Reply to this email directly, view it on GitHub<https://github.com/kaspermunch/slurm-jupyter/pull/4#issuecomment-1210552754>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAI46BBVZSHIUYWHBYDZRCDVYOH75ANCNFSM55VKJ3HA>.
You are receiving this because you commented.Message ID: ***@***.***>